name: CI

env: 
  DOTNET_VERSION: '8.x'                     # la versión de .NET 
  SONAR_ORG: 'gabrielfmh'                   # Nombre de la organización de 
  SONAR_PROJECT: 'gabrielfmh_bloodbank'     # Key ID del proyecto de sonar 
  VSTEST_TIMEOUT: 120000


on: 
  push: 
    branches: [ "main" ] 
  pull_request:
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Clean Build
      run: dotnet clean ProyectoFinal/Proyecto_Final_Blood_Bank.sln



    - name: Restore dependencies
      run: dotnet restore ProyectoFinal/Proyecto_Final_Blood_Bank.sln

    - name: Remove feature.cs files
      run: Remove-Item -Path '**/*.feature.cs' -Force



    - name: Build solution
      run: msbuild ProyectoFinal/Proyecto_Final_Blood_Bank.sln /p:Configuration=Release /p:SkipSpecFlowTargets=true /p:Platform="Any CPU"

    - name: Generate Test Report
      run: reportgenerator "-reports:./TestResults/**/*.trx" "-targetdir:TestResults/report" -reporttypes:Html
    
    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: Coverage Report
        path: TestResults/**/*.xml
    
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '**/*.trx'

