name: CI

env: 
  DOTNET_VERSION: '8.x'                     # la versión de .NET 
  SONAR_ORG: 'gabrielfmh'                   # Nombre de la organización de 
  SONAR_PROJECT: 'gabrielfmh_bloodbank'     # Key ID del proyecto de sonar 

on: 
  push: 
    branches: [ "main" ] 
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      run: dotnet restore ProyectoFinal/Proyecto_Final_Blood_Bank.sln

    - name: Build solution
      run: msbuild ProyectoFinal/Proyecto_Final_Blood_Bank.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run tests
      run: dotnet test ProyectoFinal/Proyecto_Final_Blood_Bank.sln --logger "trx;LogFileName=test_results.trx"

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '**/*.trx'
