name: CI

env: 
  DOTNET_VERSION: '8.x'                     # la versión de .NET 
  SONAR_ORG: 'gabrielfmh'                   # Nombre de la organización de 
  SONAR_PROJECT: 'gabrielfmh_bloodbank'     # Key ID del proyecto de sonar 
  VSTEST_TIMEOUT: 120000


on: 
  push: 
    branches: [ "main" ] 
  pull_request:
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Clean Build
      run: dotnet clean ProyectoFinal/Proyecto_Final_Blood_Bank.sln



    - name: Restore dependencies
      run: dotnet restore ProyectoFinal/Proyecto_Final_Blood_Bank.sln

    - name: Remove feature.cs files
      run: Remove-Item -Path '**/*.feature.cs' -Force



    - name: Build solution
      run: msbuild ProyectoFinal/Proyecto_Final_Blood_Bank.sln /p:Configuration=Release /p:SkipSpecFlowTargets=true /p:Platform="Any CPU"

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
            

    - name: Generate msbuild project file
      uses: tix-factory/msbuild-project-generator@v1
      with:
        directory: ./
        projectFile: ./build.project

    - name: Run tests
      run: |
        dotnet test ProyectoFinal/Proyecto_Final_Blood_Bank.sln `
          --logger "trx;LogFileName=test_results.trx" `
          --no-build `
          --configuration Release
      
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '**/*.trx'

