name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET 
  SONAR_ORG: 'gabrielfmh'                   # Nombre de la organización de Sonar
  SONAR_PROJECT: 'gabrielfmh_bloodbank'     # Key ID del proyecto de Sonar

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore ProyectoFinal/Proyecto_Final_Blood_Bank.sln

    - name: Build Solution
      run: msbuild ProyectoFinal/Proyecto_Final_Blood_Bank.sln /p:Configuration=Release /p:Platform="AnyCPU" /m

    - name: Test Project
      run: |
        $testProjects = Get-ChildItem -Path ProyectoFinal/ -Recurse -Filter *.Tests.csproj
        foreach ($testProject in $testProjects)
        {
          dotnet test $testProject.FullName --no-build --logger "trx;LogFileName=${{ github.workspace }}/${{ testProject.Name }}.trx"
        }

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '*.trx'
